name: Build and Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      linux-artifacts: ${{ steps.upload-artifacts.outputs.artifacts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run make -- --platform=linux

      - name: Upload Linux Build Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: ./out/keep/

  build-windows:
    runs-on: ubuntu-latest
    outputs:
      windows-artifacts: ${{ steps.upload-artifacts.outputs.artifacts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Mono and Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get -y update
          sudo apt-get -y install wine32 wine64 mono-devel

      - name: Build for Windows
        run: npm run make -- --platform=win32

      - name: Upload Windows Build Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: ./out/keep/

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-build

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-build

      - name: Create release and upload assets
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./out/keep/**
          tag_name: v${{ env.VERSION }}
          name: InterestPlanner ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
