name: Build and Release

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      linux-artifacts: ${{ steps.upload-artifacts.outputs.artifacts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Linux
        run: npm run make -- --platform=linux

      - name: List output directory
        run: ls -R out/

      - name: Upload Linux Build Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-build
          path: |
            out/make/**/*.deb
            out/make/**/*.rpm

  build-windows:
    runs-on: windows-latest  # Changed to windows-latest for better Windows builds
    outputs:
      windows-artifacts: ${{ steps.upload-artifacts.outputs.artifacts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run make -- --platform=win32

      - name: List output directory
        run: dir /s out

      - name: Upload Windows Build Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: |
            out/make/**/*.exe
            out/make/**/*.msi
            out/make/**/RELEASES

  build-macos:
    runs-on: macos-latest
    outputs:
      macos-artifacts: ${{ steps.upload-artifacts.outputs.artifacts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build for macOS
        run: npm run make -- --platform=darwin

      - name: List output directory
        run: ls -R out/

      - name: Upload macOS Build Artifacts
        id: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: out/make/**/*.zip

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows, build-macos]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Dist Directory
        run: mkdir -p dist

      - name: Download Linux Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: dist/linux

      - name: Download Windows Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: dist/windows

      - name: Download macOS Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: dist/macos

      - name: Display structure of downloaded files
        run: ls -R dist/

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*
          tag_name: v${{ env.VERSION }}
          name: InterestPlanner ${{ env.VERSION }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
